### ISSUE TITLE
Home Page Discussion

### ISSUE THREAD

**Issue by robmoffat** [risk-first/website#1]
Comment Here

**Comment by ThomasJason** [comment]
@robmoffat I'd like to contact you privately about this book, how do I do that?

**Comment by robmoffat** [comment]
Sure, email me-  rob at kite9.com

**Comment by robmoffat** [comment]
@ThomasJason I'd like to close this issue down- did you still want to get in touch?

**Comment by ThomasJason** [comment]
I do, go ahead and close this. Late next week when I’m back I’ll reach out.

**Comment by robmoffat** [comment]
ta
