### ISSUE TITLE
Use gender neutral term "Key Person" instead of "Key Man"

### ISSUE THREAD

**Issue by georgebashi** [risk-first/website#10]
...because there are lots of key people out there who aren't men 🙂

The wikipedia page that is linked from the text is already named "Key Person ..." so there's precedent for this term there. I don't think it changes the meaning or makes it less easy comprehensible either, but is a bit more inclusive.

I've changed the occurrences I could find: https://github.com/georgebashi/risk-first/commit/2f35f385cf78ce27443a861ef25ace1572fb9f56

I've also tidied up the inconsistency in usage between hyphenated and non-hyphenated. Totally a style thing so let me know if you prefer the hyphenated version and I'll push a new commit.

Thanks a lot for a really practical, down-to-earth and informative read!

**Comment by robmoffat** [comment]
Thanks for this.  I've still not seen a good article on how to do pull requests for a github wiki, it seems like it's broken and I don't know the workaround.  However, I've incorporated your changes as best I can.

Thanks for finding all the instances.  I've gone with your suggestion of "Key Person Risk" across the board.  

Also I've added you on the https://github.com/risk-first/website/wiki/Contributors page.  Hope that's ok?

thanks again!
