### ISSUE TITLE
use single term for pay-off

### ISSUE THREAD

**Issue by hovancik** [risk-first/website#11]
There are different terms right now: 
Pay-Off, Pay off, Pay Off

https://github.com/risk-first/website/wiki/Meeting-reality#pay-off

Seems that Payoff or Pay off are the correct ones. Usage of Payoff makes the biggest sense to me.  

https://www.merriam-webster.com/dictionary/payoff

**Comment by robmoffat** [comment]
I agree that capitalised "Payoff" should be the correct spelling.  I've been through it and updated all of those.

I've also added you to the https://github.com/risk-first/website/wiki/Contributors page.  Thanks for your help!

**Comment by hovancik** [comment]
Reading on and I see that some images will need to be updated as well: 
https://github.com/risk-first/website/wiki/Evaluating-Risk#risk-matrix

**Comment by robmoffat** [comment]
Updated the images, and fixed the justification of the labels too.
