### ISSUE TITLE
All Risk Management page feedback

### ISSUE THREAD

**Issue by bertold** [risk-first/website#12]
A few comments for the 
https://github.com/risk-first/website/wiki/All-Risk-Management page:

* the dots at the end of section titles should be removed (Every Action Has Attendant Risk., Every Decision Is About PayOff.)
* the last section link actually links to the page that is two sections before the current one. This is inconsistent

**Comment by robmoffat** [comment]
Thanks again, Bertold.  

This should be fixed now.
