### ISSUE TITLE
Move Wiki to gh-pages

### ISSUE THREAD

**Issue by robmoffat** [risk-first/website#14]
As discussed in Gustavo's PR, gh-pages might be a better way to host this content than github wiki

https://github.com/risk-first/website/pull/13

@gandrade

**Comment by hovancik** [comment]
There is a [Github Pages Examples](https://github.com/collections/github-pages-examples) with some well done docs via GH Pages done, for inspiration. Especially folks at Electron has done great job: https://github.com/electron/electronjs.org

**Comment by robmoffat** [comment]
Would appreciate some feedback:  https://riskfirst.org
