### ISSUE TITLE
Missing `www` CNAME DNS entry

### ISSUE THREAD

**Issue by gandrade** [risk-first/website#18]
Folks, 

I've tried to access Risk First website typing [www.riskfirst.org](www.riskfirst.org), but it seems that it wasn't configured. I guess that creating a CNAME DNS entry for `www` would be enough to solve it.

Does it make sense?

**Comment by robmoffat** [comment]
Hi Gustavo,

I think this is fixed for me now- does it work for you?

**Comment by gandrade** [comment]
Now, it's working fine. 
Thanks for fix it.
