### ISSUE TITLE
Rapid Feedback loop

### ISSUE THREAD

**Issue by stephanwesten** [risk-first/website#2]
Hi,

I quickly read through the risks section. What I miss is the rapid feedback loop. 
A way to mitigate risks is to get rapid feedback. Why is this important? Because the biggest risk, delivering the wrong feature, can only be addressed by users actually using the system. So risks are indeed a factor, but so is time. 

Like you describe the internal model. The internal model changes with time.  Not only because of our growing insight, but also because the world we live in changes and so does the context of our software. 

BTW A developer making changes in production is not necessarily a disaster; provided that the risks are small / acceptable and the value the change brings, information / feedback, compensates for the risk. Like for a website a small bug is a not as disastrous as it would be for a bank. Especially nowadays in the micro services world where we architect with failure in our design. (E.g. a rating service in a website temporarily off line)

In the ideal world the developer makes the changes in production to get the most rapid feedback. In most cases this is not acceptable, because of the risks as you point out. However most of the things we do to mitigate risks, also slows us down. Here is the trade-off you need to make. 

HTH

Stephan

**Comment by robmoffat** [comment]
Hi Stephan,  

Thanks for your feedback.   Yes, feedback is super-important, I agree.   I've tried to cover this in both [Meeting Reality](https://github.com/risk-first/website/wiki/Meeting-Reality) and [Cadence](https://github.com/risk-first/website/wiki/Cadence).   Perhaps you can take a look at those and let me know if I've covered in sufficiently?

> Like you describe the internal model. The internal model changes with time. Not only because of our growing insight, but also because the world we live in changes and so does the context of our software.

Absolutely.  This is totally what I'm trying to get across.  

> BTW A developer making changes in production is not necessarily a disaster; provided that the risks are small / acceptable and the value the change brings, information / feedback, compensates for the risk. Like for a website a small bug is a not as disastrous as it would be for a bank. Especially nowadays in the micro services world where we architect with failure in our design. (E.g. a rating service in a website temporarily off line)

Good spot, I've updated the text to be a bit less alarmist:  

> We can all see this might end in disaster, but why?

Is that enough?

If it's ok with you, I've credited you on the [Contributors](https://github.com/risk-first/website/wiki/Contributors) page.
