### ISSUE TITLE
Broken link in Meeting Reality

### ISSUE THREAD

**Issue by ianobermiller** [risk-first/website#3]
> We should be able to weigh these separate risks in our hands and figure out whether the (Glossary#pay-off) makes a given Action worthwhile.

The term Pay Off is not properly linkified. I'd send a PR but there doesn't appear to be a way to do so.

**Comment by robmoffat** [comment]
Fixed in: 3489df9e35f58ff820b8ed5d9403b0a343f2c7e4

**Comment by robmoffat** [comment]
thanks ianobermiller!
