### ISSUE TITLE
Wrong link in Evaluating Risk

### ISSUE THREAD

**Issue by ianobermiller** [risk-first/website#4]
> Third, as soon as you publish a date it changes the expectations of the project (see Student Syndrome).

Student syndrome should link [here](https://github.com/risk-first/website/wiki/Scarcity-Risk#student-syndrome), but instead links to [Schedule Risk](https://github.com/risk-first/website/wiki/Scarcity-Risk#schedule-risk).

**Comment by robmoffat** [comment]
Fixed now, thanks.  

I've credited you on the [Contributors](https://github.com/risk-first/website/wiki/Contributors) page, hope that's ok?

**Comment by ianobermiller** [comment]
> I've credited you on the Contributors page, hope that's ok?

That's very kind of you! I've really enjoyed your writing and the fresh take on software project management!
