### ISSUE TITLE
Double negation / extra isn't on A Pattern Language page

### ISSUE THREAD

**Issue by bertold** [risk-first/website#5]
I find that the following sentence in the "What This is Not" section of 
https://github.com/risk-first/website/wiki/A-Pattern-Language has an extra "isn't":

> Neither is this site **isn't** going to be an exhaustive guide

**Comment by robmoffat** [comment]
Fixed, thanks so much for posting the issue.

Credited you here:  https://github.com/risk-first/website/wiki/Contributors

hope that's ok.
