### ISSUE TITLE
Capitalization issues in Audience section

### ISSUE THREAD

**Issue by bertold** [risk-first/website#6]
In the 2nd and 3rd paragraph of , "This" starts with a capital T (which I don't think is proper). See bolded T-s below:

> But here's a warning: **T**his is going to be a depressing book to read. It is book one of a two-book series, but in Book One you only get to meet the bad guy.
> 
> While Book Two is all about how to succeed, **T**his book is all about

**Comment by robmoffat** [comment]
You uncovered a big one here, capitalisation after colons was massively inconsistent.  Hopefully fixed now.

Thanks again for your help!
