### ISSUE TITLE
Consider changing adding other roles or revise developer role in the Audience section 

### ISSUE THREAD

**Issue by bertold** [risk-first/website#7]
I feel that the audience section should also include engineers wearing roles other than Developers:
https://github.com/risk-first/website/wiki/Audience

Even though I have not read the book yet, I really do hope that the book will be a useful resource for teams where the developer / tester roles are still segregated. Maybe using a more general term like engineers or those working in the trenches (individual contributors) would be more appropriate. I am pretty sure that the risk management is important in testing activities.

**Comment by robmoffat** [comment]
Updated. Thanks once again!
