### ISSUE TITLE
Quick Summary page feedback

### ISSUE THREAD

**Issue by bertold** [risk-first/website#8]
On the https://github.com/risk-first/website/wiki/Quick-Summary page I have found that the capitalization of "Can" is inconsistent in the section titles: in section 2 and 3, "can" starts with an uppercase C, in section 4 and 6, "can" starts with a lowercase "C".

In Section 4, the link is to a Key-Man Risk, but the page is titled Coordination Risk. Should the link text be updated to reflect this?

**Comment by robmoffat** [comment]
Fixed, thanks

**Comment by robmoffat** [comment]
Fixed Key-Man -> Key Person too
