### ISSUE TITLE
A Simple Scenario page feedback

### ISSUE THREAD

**Issue by bertold** [risk-first/website#9]
Comments on the https://github.com/risk-first/website/wiki/A-Simple-Scenario page:

2nd paragraph:
> Lets for a moment ...

Maybe this should be changed to "Let's - for a moment - " ..

In the "Hidden Risks" section, I would change the following sentence:
> The difference is, Attendant Risks are risks you are aware of, but **can't be** sure of the amount they will impact you

I feel that "can't" is a strong word here. I would replace that with "may not be". I feel that it is universally not necessarily true that the impact of attendant risks are unknown. Of course, unless I misunderstood the definition.

**Comment by robmoffat** [comment]
Rewrote it: 

https://github.com/risk-first/website/wiki/A-Simple-Scenario#hidden-risks

**Comment by bertold** [comment]
It looks much more polished. Thank you. Feel free to close.

**Comment by robmoffat** [comment]
thanks Bertold!
